### ISSUE TITLE
404 for JavaScript assets

### ISSUE THREAD

**Issue by atodorov** [burke-software/django-report-builder#295]
I am using the 6.1 version that you published on Friday. I get 404 for the following files:

```
[06/Aug/2018 07:51:06] "GET /static/report_builder/styles.bundle.css HTTP/1.1" 404 1720
[06/Aug/2018 07:51:06] "GET /static/report_builder/inline.bundle.js HTTP/1.1" 404 1717
[06/Aug/2018 07:51:06] "GET /static/report_builder/polyfills.bundle.js HTTP/1.1" 404 1726
[06/Aug/2018 07:51:06] "GET /static/report_builder/main.bundle.js HTTP/1.1" 404 1711
[06/Aug/2018 07:51:06] "GET /static/report_builder/main.bundle.js HTTP/1.1" 404 1711
[06/Aug/2018 07:51:06] "GET /static/report_builder/styles.bundle.css HTTP/1.1" 404 1720
```

and they are not to be found in the source. If this is a quick fix can you patch it ASAP ?

**Comment by bufke** [comment]
There was a mistake made in releasing 6.2.0. Fixed in 6.2.1. Thanks.

**Comment by atodorov** [comment]
I've updated to django-report-builder==6.2.1 and I still see the same issue.

**Comment by bufke** [comment]
Hmm yes, not sure what's going on.

**Comment by bufke** [comment]
Try it again, seems like the file names changed at some point. Guessing a change in angular-cli.

**Comment by atodorov** [comment]
6.2.2 seems to work but maybe you should add some tests for these files.

**Comment by bufke** [comment]
Feel free to contribute any ideas - unfortunately this type of issue is hard to test as only an end to end test could possibly catch it. Furthermore we would need to build assets on CI and then run the test. I think it's very doable but I do not have time for it. If you wanted to take on I think it would look like:

- New build step in gitlab CI to build static assets
- New step to test django app with static assets, (cheap way - sanity check assets exists, better way actually run a headless browser and do a sanity check that the frontend is working with the backend)
- New deploy step that would include authentication to pypi and submit the finished build - perhaps based on tags. Currently builds are done manually outside of CI which is of course error prone.

Let me know if you think you can help! Thanks.
